app:
  name: customer-c
  group: customer-c
  replicaCount: 5
  container:
    image: image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest
    port: 8080
    config: []
    env: 
      - key: key
        value: value
  service:
    type: ClusterIP
    port: 8080
